### ISSUE TITLE
[SUGGESTION] Config stash for apartments

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-apartments#102]
**Is your feature request related to a problem? Please describe.**
Should be a config for stash size, seems like a no brainer :)

**Describe the feature you'd like**
Bascially this table thingo that Lionheart referred to: https://discord.com/channels/831626422232678481/977648270031605811/977710882543009873

**Describe alternatives you've considered**
Manually adding 
`lua
TriggerServerEvent("inventory:server:OpenInventory", "stash", "StashName", {
        maxweight = 1500000,
        slots = 50,
    })`

**Additional context**

**Comment by PavilonGaming** [comment]
1000% need this
