### ISSUE TITLE
[BUG] Drawtext showing for 1 second then disappearing while in polyzone

### ISSUE THREAD

**Issue by complexza** [qbcore-framework/qb-apartments#113]
**Describe the bug**
Drawtext only shows for 1second then goes away while in Polyzone for stash etc

**To Reproduce**
1. Go in to the apartments, Go to stash or any other location like clothing etc,
2. See drawtext not showing for more then 1 second

**Expected behavior**
For it to stay on screen when in the Polyzone

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] latest update
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] no
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Comment by Zakrosus** [comment]
Did u get help ?

**Comment by complexza** [comment]
> Did u get help ?
> 
> 

This is soo old, I solved it myself, Cant remember what I did
