### ISSUE TITLE
[BUG] cant get outof the apartment

### ISSUE THREAD

**Issue by Snili866** [qbcore-framework/qb-apartments#116]
when i spawn in my apartment and walk too the door the menu too get out wont show up,but when i was walkin around too see if the go out menu would appear somewhere else i found it behind the sofa....how can i fix this??

**Comment by Schweinejaeger** [comment]
Bei mir hat es geholfen, die letzer Änderung in client main.lua in Zeile 197 rückgängig zu machen.
Hier wurde warum auch immer + anstatt - Zeichen verwendet, danach ging es wieder bei mir.
Korrekte Zeile:
`local entrancePos = vector3(Apartments.Locations[ClosestHouse].coords.enter.x - POIOffsets.exit.x, Apartments.Locations[ClosestHouse].coords.enter.y - POIOffsets.exit.y - 0.5, Apartments.Locations[ClosestHouse].coords.enter.z - CurrentOffset + POIOffsets.exit.z)`

**Comment by kushuser** [comment]
changing client main.lua line 197 from plus to negative signs worked, cheers
