### ISSUE TITLE
[BUG] Apartment.Starting = False Not letting players inside

### ISSUE THREAD

**Issue by xastr0** [qbcore-framework/qb-apartments#117]
**Describe the bug**
Every time i set the Apartment.Starting to false the players are not able to use the apartments at all, the blips to show where they are disappeared, when you go to the to the vector- it shows the menu, you click "Move Here" and it doesnt let players go inside. 

**To Reproduce**
1. Go to 'qb-apartment/config.lua '
2. Click on apartment.starting = false.'
3. restart- blips disappear/ can't enter apartment

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [7/31/2023]
 - Are you using custom resource? which ones? removed qb-clothing to illeium appearnace - 
 - Have you renamed `qb-` to something custom? [no]

**Additional context**

**Comment by UwUway** [comment]
it's because it only inserts into the database when you apartment.starting = true, you'll have to update the update event to insert into the database if its not already present

**Comment by JonnyShertz** [comment]
> it's because it only inserts into the database when you apartment.starting = true, you'll have to update the update event to insert into the database if its not already present

And how would you do that? Having the same issue

**Comment by BARISHU-code** [comment]
I have solved this problem and I have also made the cost of moving and the first purchase in apartment buildings 5000$.

**Comment by fivemelite** [comment]
> I have solved this problem and I have also made the cost of moving and the first purchase in apartment buildings 5000$.

how did u do that can u send me the code

**Comment by oofbloxwastaken** [comment]
> I have solved this problem and I have also made the cost of moving and the first purchase in apartment buildings 5000$.

If you are gonna solve the problem and not show how then don't say anything.

**Comment by BARISHU-code** [comment]
Hi just saw your messages, friends, I will share the solved version in my own profile, you can edit it according to yourself.

**Comment by Ptaxal** [comment]
> **Describe the bug** Every time i set the Apartment.Starting to false the players are not able to use the apartments at all, the blips to show where they are disappeared, when you go to the to the vector- it shows the menu, you click "Move Here" and it doesnt let players go inside.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'qb-apartment/config.lua '
> 2. Click on apartment.starting = false.'
> 3. restart- blips disappear/ can't enter apartment
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Questions (please complete the following information):**
> 
> * When you last updated: [7/31/2023]
> * Are you using custom resource? which ones? removed qb-clothing to illeium appearnace -
> * Have you renamed `qb-` to something custom? [no]
> 
> **Additional context** Add any other context about the problem here.

My config qb-apartments:
```
Apartments = {}
Apartments.Starting = false
Apartments.SpawnOffset = 30
Apartments.Locations = {
    ["apartment1"] = {
        name = "apartment1",
        label = "South Rockford Drive",
        coords = {
            enter = vector4(-667.02, -1105.24, 14.63, 242.32),
        },
```
My config qb-multicharacter:
```
[Config = {}
Config.Interior = vector3(-814.89, 181.95, 76.85) -- Interior to load where characters are previewed
Config.DefaultSpawn = vector3(-1035.71, -2731.87, 12.86) -- Default spawn coords if you have start apartments disabled
Config.PedCoords = vector4(-813.97, 176.22, 76.74, -7.5) -- Create preview ped at these coordinates
Config.HiddenCoords = vector4(-812.23, 182.54, 76.74, 156.5) -- Hides your actual ped while you are in selection
Config.CamCoords = vector4(-813.46, 178.95, 76.85, 174.5) -- Camera coordinates for character preview screen
Config.EnableDeleteButton = true -- Define if the player can delete the character or not
Config.customNationality = false -- Defines if Nationality input is custom of blocked to the list of Countries
Config.SkipSelection = true -- Skip the spawn selection and spawns the player at the last location

Config.DefaultNumberOfCharacters = 1 -- Define maximum amount of default characters (maximum 5 characters defined by default)
Config.PlayersNumberOfCharacters = { -- Define maximum amount of player characters by rockstar license (you can find this license in your server's database in the player table)
    { license = "license:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", numberOfChars = 2 },
}](url)
```

These settings allow you to completely disable apartments on loading, character creation... as well as disable the selection of a spawn point if you don't need it.

**Comment by Fgselman** [comment]
Someone who can help me, I have tried everything above and nothing works! Look at the video below 
https://medal.tv/games/gta-v/clips/24pDi1-gI_e4pi/d1337uDFBCOs?invite=cr-MSxvbXIsMTU3MTg1MjMyLA

**Comment by Ptaxal** [comment]
I don't understand what the question is, If it doesn't work from the
beginning, it's sad, if not, I don't understand what you've done or what
needs to be done, please tell me more, maybe I can help you.

ср, 3 апр. 2024 г. в 15:24, Fgselman ***@***.***>:

**Comment by Fgselman** [comment]
I dont know what I have done and I dont get any errors, but everytime i relogg my apartment will not be saved, and when i enter the game and move to a new one it wont let me enter, (like i show in the video)
