### ISSUE TITLE
[BUG] Setting Apartments.Starting = False bringing issues...

### ISSUE THREAD

**Issue by ebkVNGE** [qbcore-framework/qb-apartments#125]
**Describe the bug**
Whenever I set Apartments.Starting to False a few things are happening. First, you don't get a ped menu, so you cannot pick your outfit and it will give you a random default ped. Second, if you try to move in to the apartment, you will not be able to enter it. There are no errors, and other people have had similar issues, none of them have been resolved.

**To Reproduce**
1. Go to qb-apartments/config.lua line 2
2. Set Apartments.Starting to false
3. Create a brand new character

**Expected behavior**
The setting to not break the script?

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: April 3rd, 2024
 - Are you using custom resource? which ones? illenium-appearance
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by Pojus** [comment]
I've the same problem after setting apartament.config to false. In my case it'll not let me spawn with pet, it'll stuck on black screen forever. I'm trying to understand if it's something with the "qb-multicharacter:client:closeNUIdefault" invoked when you set apartament.config to false but not sure

**Comment by KeepItLokiTho** [comment]
running into this same issue on a fresh install of qb-core with only this config setting changed as well
