### ISSUE TITLE
[BUG] Can't get out of Apartments

### ISSUE THREAD

**Issue by Hiperinio** [qbcore-framework/qb-apartments#21]
**Describe the bug**
When you spawn and select the apartment you can't get out of it.

**To Reproduce**
1. Install fresh qbcore version
2. Create new character and spawn

**Expected behavior**
To be able to get out of the apartment

**Questions (please complete the following information):**
 - When you last updated: few minutes ago
 - Are you using custom resource? which ones?: no, fresh install
 - Have you renamed `qb-` to something custom?: no

**Comment by CyclopsGM01** [comment]
The same problem with me also, Did everything mentioned but still not working!

**Comment by DieVlakVark** [comment]
Also did a complete new installation and nothing still stuck

**Comment by Milk-Bandit** [comment]
Same for me. Cannot leave or enter apartments. This is a new seperate fresh install without custom resources so far

**Comment by Milk-Bandit** [comment]
![image](https://user-images.githubusercontent.com/90882267/134813288-4f74a3b5-b8c0-417a-a791-b8438c74791c.png)
Update, finally got this as an F8 appearance

**Comment by RexShack** [comment]
same here after updating to new qb-apartments

**Comment by GhzGarage** [comment]
Try this https://github.com/qbcore-framework/qb-apartments/commit/e2419ffc80983b81a6d7772b90a6631de0dbf5e9

**Comment by Hiperinio** [comment]
It's working now. But when you use the last location it spawns you to the apartment room ( that was before the update aswell )

**Comment by GhzGarage** [comment]
The core saves your position on logout and leaving the server

**Comment by GhzGarage** [comment]
Or do you mean if you leave the apartment and then logout of the server and come back it puts you in the apartment?

**Comment by Hiperinio** [comment]
It works now, tried it again and works as intended. The problem before the commit was that after you leave the server and log in again it spawned you back to your apartment but now it's working. Thanks for the commit <3
