### ISSUE TITLE
[BUG] Can't get in into the apartments

### ISSUE THREAD

**Issue by Branqueador** [qbcore-framework/qb-apartments#23]
Updated with all the lastest and it does not have the Text to go in into the apartment

**Questions (please complete the following information):**
 - When you last updated: just now
 - Are you using custom resource? which ones? : yes qb-target, 710-carfobs,dox-garage,polyzone
 - Have you renamed `qb-` to something custom? : no
Start Server, create a character get out of the apartment , restart server
![image](https://user-images.githubusercontent.com/37988563/134817309-47364d17-7871-40b4-9123-2f9e208f7100.png)

**Comment by Branqueador** [comment]
Fixed by creating new character

**Comment by HATE-dev** [comment]
are there any erros?

**Comment by ihyajb** [comment]
Could not reproduce. Using latest QBCore resources. 

![image](https://user-images.githubusercontent.com/66404074/135008899-d547db3e-7edb-4a87-8ebe-05cc711417e5.png)

**Comment by Branqueador** [comment]
i think the problem was being caused either by not having ambulance updated or idk fixed anyway! Thanks
