### ISSUE TITLE
Stash

### ISSUE THREAD

**Issue by Slay3rIQ** [qbcore-framework/qb-apartments#27]
Can't open my stash in the apartment.

![image](https://user-images.githubusercontent.com/90642225/135135581-27866a8c-21ea-4aae-af71-89aee29b784d.png)

**Comment by ihyajb** [comment]
any errors in f8?

**Comment by Slay3rIQ** [comment]
No Sir.

**Comment by Eralpozcan** [comment]
Can you open another stash?

**Comment by Slay3rIQ** [comment]
> Can you open another stash?

No

**Comment by Eralpozcan** [comment]
Download and install the latest version qb-inventory. Try the problem again.

**Comment by Slay3rIQ** [comment]
> Do you have the same problem with glovebox?. Download and install the latest version qb-inventory. Try the problem again.

I download the last version and still the same issue

**Comment by tony-stark-17** [comment]
> > Do you have the same problem with glovebox?. Download and install the latest version qb-inventory. Try the problem again.
> 
> I download the last version and still the same issue

Does your E button work ?
