### ISSUE TITLE
[BUG] apartments action

### ISSUE THREAD

**Issue by SubDataa** [qbcore-framework/qb-apartments#28]
**Describe the bug**
After creating character and choose apartments, No text appears (Stash, log out, Leave apartments etc..) We have to reboot server for the text to appear

**To Reproduce**
1. Create new character
2. Choose an apartments and spawn

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? no
 - Have you renamed `qb-` to something custom? no

**Comment by tomasalves8** [comment]
Could not reproduce.

**Comment by Rhydium** [comment]
Couldn't reproduce either.

**Comment by justshoveit** [comment]
Couldn't reproduce.
