### ISSUE TITLE
[BUG] Players sometime enter same apartment instead of their own

### ISSUE THREAD

**Issue by Dankbudbaker** [qbcore-framework/qb-apartments#36]
**Describe the bug**
I have noticed on my server when my group get done with heist and we all try to enter our own apartments to store the goods we got. that if we all in the same moment click to enter our apartments that sometimes they will spawn in my apartment instead of their own apartment. 

**To Reproduce**
1. have a group (i had about 4 with me) enter their apartment at the same time
2. when entering apartment randomly the group will enter same apartment. 

**Expected behavior**
i expect for everyone to enter their own apartment

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: as soon as a new commit is published i update.
 - Are you using custom resource? all my resources have came from your github.
 - Have you renamed `qb-` to something custom?  nope i didnt rename anything

**Comment by ITSJORDAN-TFA** [comment]
Can confirm I have also had this error in the past with around 5 people entering the same apartment, idk if there is a way to create network instances in GTA like they do online?
