### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by WEEZOOKARP** [qbcore-framework/qb-apartments#42]
**Describe the bug**
When attempting to enter my apartment or buy or move into a new one the menu is unusable, it doesn't show my cursor and arrow keys etc do nothing

**To Reproduce**
1. Go to an apartment
2. attempt to access apartment

**Expected behavior**
I mean I expected to be able to actually use the menu to access the apartments

**Screenshots**
(https://cdn.discordapp.com/attachments/446201646687584257/912999539370246154/unknown.png)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 I used the txadmin recipe and the issue started there when I couldn't even exit the apartment is started in I reinstalled it off github and same issue persists
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 no custom resources that arent in the qbcore recipe for txadmin
 - Have you renamed `qb-` to something custom? [e.g. yes/no]
 no

**Additional context**
I couldn't even leave my starting apartment after creating my character and none of the interactions in the apartment worked

**Comment by WEEZOOKARP** [comment]
Update i have to press alt for my mouse to appear but when I try to access my apartment it just doesn't let me in when I click the enter apartment button

**Comment by WEEZOOKARP** [comment]
fixed but still need to press alt to use house and apartment menus require alt

**Comment by GhzGarage** [comment]
Yes it’s intended to press the give focus key to interact with the menu
