### ISSUE TITLE
[BUG] Multiple person in the same appartment 

### ISSUE THREAD

**Issue by Ranger194** [qbcore-framework/qb-apartments#46]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. When you join the server for the first time, with other players and choose the same appartment,  the ped spawn above other player ped, and its impossible to create the character
2. If your inside the appartment, and a player join for the first time you can see him customizing the ped.

**Expected behavior**
players staying invisible for each other

**Questions (please complete the following information):**
 - When you last updated: lask week
 - Have you renamed `qb-` to something custom? no

**Comment by FjamZoo** [comment]
This is fixed with 
https://github.com/qbcore-framework/qb-apartments/pull/50
