### ISSUE TITLE
stash and outfits [BUG]

### ISSUE THREAD

**Issue by Andyauk** [qbcore-framework/qb-apartments#67]
**Describe the bug**
when you go into your apartment and use stash or outfits, it shows up but nothing happens when you press E.
(I will try change apartment's, when I wake up. see if that helps. after thinking about it.) 

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by Haz231** [comment]
Having the same issue.

**Comment by deandum** [comment]
> **Describe the bug** when you go into your apartment and use stash or outfits, it shows up but nothing happens when you press E. (I will try change apartment's, when I wake up. see if that helps. after thinking about it.)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Use this item '....' (item's name from shared.lua if applicable)
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Questions (please complete the following information):**
> 
> * When you last updated: [e.g. last week]
> * Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
> * Have you renamed `qb-` to something custom? [e.g. yes/no]
> 
> **Additional context** Add any other context about the problem here.

Make sure you are on version `2.1.0`:
https://medal.tv/games/gta-v/clips/gktBRlw1dVd7e/d13372qTNdlx?invite=cr-MSx2SzMsMzc4Nzc2MzMs

**Comment by Andyauk** [comment]
> > **Describe the bug** when you go into your apartment and use stash or outfits, it shows up but nothing happens when you press E. (I will try change apartment's, when I wake up. see if that helps. after thinking about it.)
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Go to '...'
> > 2. Click on '....'
> > 3. Use this item '....' (item's name from shared.lua if applicable)
> > 4. See error
> > 
> > **Expected behavior** A clear and concise description of what you expected to happen.
> > **Screenshots** If applicable, add screenshots to help explain your problem.
> > **Questions (please complete the following information):**
> > 
> > * When you last updated: [e.g. last week]
> > * Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
> > * Have you renamed `qb-` to something custom? [e.g. yes/no]
> > 
> > **Additional context** Add any other context about the problem here.
> 
> Make sure you are on version `2.1.0`: https://medal.tv/games/gta-v/clips/gktBRlw1dVd7e/d13372qTNdlx?invite=cr-MSx2SzMsMzc4Nzc2MzMs

Yes it all fine now, this was back when it had the old PR, this can be removed.
