### ISSUE TITLE
[Suggestion] Police can enter any apartment with a /raid (citizenid) command

### ISSUE THREAD

**Issue by GravityRoleplay** [qbcore-framework/qb-apartments#77]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the feature you'd like**
A The ability for police to enter anyones apartment using there citizen id, this would be a good feature as it'll allow police to enter apartments for raids without the person being raided having any knowledge of it

**Describe alternatives you've considered**
A Trying to implement it myself but currently struggling

**Additional context**

**Comment by badcodestv** [comment]
@GravityRoleplay I did something that you can use. 
![image](https://user-images.githubusercontent.com/56496943/184428999-64580ed0-9261-4347-b48e-a76ff8ed84b1.png)
![image](https://user-images.githubusercontent.com/56496943/184429012-7b57dcfb-f3bc-489d-8462-d8b834452cc3.png)

This utilizes qb-input and qb-target. I've tried to modify this to default qbcore as best as I could for ya, but it should work out of the box here.

In your police job script, you'll want to create an export for people who can raid hence why there's a check for canInteract on the apartment target `exports['police']:CanRaid()`. 

**Police Script config.lua**
` Config.RaidLevel = -- set ur level here`

**Police Script client file**
`exports("CanRaid", function()
    local retval = false
    local PlayerData = FiveMCore.Functions.GetPlayerData()
    if PlayerJob.name == "police" and PlayerData.job.grade.level >= Config.RaidLevel and onDuty then
        retval = true
    end
    return retval
end)`

**In your qb-apartments/client file:**
`
Citizen.CreateThread(function()
	for k,v in pairs(Apartments.Locations) do
		exports['qb-target']:AddBoxZone('ApartmentRaid-'..k, vector3(v.coords.enter.x, v.coords.enter.y, v.coords.enter.z), 2.0, 2.0, {
			name='ApartmentRaid-'..k,
			heading=v.coords.enter.h,
			debugPoly=false,
			minZ=v.coords.enter.z - 3.0,
			maxZ=v.coords.enter.z + 3.0,
			}, {
			options = {
				{
					type = "",
					event = "",
					icon = "fa fa-th-large",
					label = "Raid Stash",
					job = "police",
					action = function(entity)
						TriggerEvent("fivem-apartments:client:TriggerMenu", v.name)
					end,
					canInteract = function(entity)
						return exports['police']:CanRaid()
					end
				}
			},
			distance = 1.5,
		})
	end
end)

RegisterNetEvent("apartments:client:RaidApartment")
AddEventHandler("apartments:client:RaidApartment", function(apartment, apartmentId, retval)
	EnterApartment(apartment, apartmentId)
end)

RegisterNetEvent("fivem-apartments:client:TriggerMenu")
AddEventHandler("fivem-apartments:client:TriggerMenu", function(name)
	local getInput = exports['qb-input']:ShowInput({
        header = "Raid Apartment",
        submitText = "Raid Apartment",
        inputs = {
            {
                text = "Apartment Number",
                name = "apartment_number",
                type = "text",
                isRequired = true
            },
        }
	})

	if getInput ~= nil then
		TriggerServerEvent("apartments:server:CheckIfOwned", name, getInput.apartment_number)
	end
end)`

**Then, on the server side in the apartment script:**

`
function getApartmentByID(apartmentId)
	local p = promise:new()
	local query = "SELECT * FROM apartments WHERE name = '" .. tostring(apartmentId) .. "'"
	exports.oxmysql:execute(query, {}, function(data)
		if data[1] ~= nil then
			p:resolve(data[1])
		else
			p:resolve(nil)
		end
	end)
	return Citizen.Await(p)
end

RegisterServerEvent("apartments:server:CheckIfOwned")
AddEventHandler("apartments:server:CheckIfOwned", function(apartment, apartmentId)
	local src = source
	local retval = getApartmentByID(apartmentId)
	if retval ~= nil then
		TriggerClientEvent("apartments:client:RaidApartment", src, apartment, apartmentId, retval)
		-- add your logger here to discord
	else
		TriggerClientEvent("QBCore:Notify", src, "No apartment found by that apartment number.")
	end
end)
`

**Comment by Zepherlah** [comment]
Did work :( I followed your steps but nothing comes up when walking towards the apartment.

**Comment by badcodestv** [comment]
@Zepherlah Join the qbcore official discord and search for the apartment thread. I posted it on there as well and plenty of folks have it working. Just look through the thread for any issues you might have and it would resolve it.

**Comment by amantu-qbit** [comment]
Unnecessary, Police can use stromarm

**Comment by rnloyola** [comment]
stormram doesnt work at apartments dude.. @amantu-qbit
