### ISSUE TITLE
[BUG] Polyzone is activated during character creation/customization 

### ISSUE THREAD

**Issue by Millusion** [qbcore-framework/qb-apartments#78]
**Describe the bug**
The new polyzones make it so that when creating a new character you get the popup to exit the apartment while inside the character customization.

**To Reproduce**
1. Make a new character
2. Pick any apartment
3. wait a couple of seconds while on character customization screen
4. See menu pop up on top of the character

**Expected behavior**
This should not happen during character creation

**Screenshots**

![afbeelding](https://user-images.githubusercontent.com/67241059/168392714-3604294b-730b-4807-8e89-0d4702df5729.png)

**Comment by troubleNZ** [comment]
i figured an easy way to work around this.
its not an issue with apartments. 
find your `qb-interiors` client main.lua

i believe the generated interior 'faces' north, and places you at the south entrance.
so set `y+2` like below in `SetEntityCoords`

```lua
function TeleportToInterior(x, y, z, h)
    CreateThread(function()
        SetEntityCoords(PlayerPedId(), x, y+2, z, 0, 0, 0, false)
        SetEntityHeading(PlayerPedId(), h)

        Wait(100)

        DoScreenFadeIn(1000)
    end)
end
```

havent tested with any other interiors, only this initial one i needed for fixing the same character creation issue

**Comment by MatthewRorke** [comment]
@Millusion please refer to the mentioned fix above

**Comment by ElvisMatias** [comment]
specifically which parameter should I modify?

**Comment by Mubarak1233** [comment]
how to create POIOffsets for apartment interior  help me
