### ISSUE TITLE
[BUG] When Apartments.Starting = false system breaks

### ISSUE THREAD

**Issue by ARSSANTO** [qbcore-framework/qb-apartments#83]
**Describe the bug**
When Apartments.Starting = false then no clothing menu coming on 1st character creations

**To Reproduce**
1. Go to qb-apartments/config/ then make  Apartments.Starting = false
2. Restart the server and try to make new character
3. everything will be fine but not clothing menu appears
4. no errors nothing 

**Expected behavior**
it should appear clothing menu without that too it was a feature 

**Questions (please complete the following information):**
 - When you last updated: [a fresh install 5 mins ago]
 - Are you using custom resource? which ones? [nop]
 - Have you renamed `qb-` to something custom? [no]

**Comment by oofbloxwastaken** [comment]
Was this resolved?
