### ISSUE TITLE
[BUG] On Logout

### ISSUE THREAD

**Issue by CxCore-xyz** [qbcore-framework/qb-apartments#85]
If you logout in the appartments with the logout off character or just exit in appartments interior when you relog back in you get teleported back to the appartment but the problem is you don't get no more like leave the apartments or stash or anything you're just stuck in the appartments

**Comment by jonihindryckx** [comment]
doesnt seem to fix this issue because im having the same problem

**Comment by CaptainP1ng** [comment]
have the same problem

**Comment by ImMacky** [comment]
I followed your instructions on how to reproduce the bug and encountered no issues on the latest release. I attempted to use the /logout command and the Logout Character Prompt at the Desk, and I was able to leave the apartments and interact with everything as expected.
