### ISSUE TITLE
[BUG] Stash Problem

### ISSUE THREAD

**Issue by ArtysV** [qbcore-framework/qb-apartments#94]
**Describe the bug**
I have very interesting bug on my fresh install qb-apartments. When someone put something in their stash. After a while this thing disappears and you can't open again the stash it's saying STASH-NONE/

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/98827458/190190955-d3c8c2dc-0e2b-4e18-af66-39f3c2ddcc0e.png)

**Questions (please complete the following information):**
 - When you last updated: The Latest one before 4-5 days
 - Are you using custom resource? which ones? zdiscord, qb-target, lj-inventory
 - Have you renamed `qb-` to something custom? No

**Additional context**

**Comment by nzkfc** [comment]
This may be your inventory, try using qb-inventory and a fresh pull to test as this does not happen on ours and multiple test cities we have.

**Comment by Wesker289** [comment]
This happens to us as well; using latest lj-inventory

**Comment by NikoClapz19** [comment]
Has this been fixed yet?

**Comment by nzkfc** [comment]
Sounds like an issue with lj inventory, go there and log a issue for then
to fix orr pull qb-inventory to your test server and see if that works
fine, then you know its not a qb-core issue as the qb inventory works fine.
